route:
  receiver: 'mail'
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'mailhog:1025'
        auth_username:
        auth_password:
        from: 'noreply@colorado.edu'
        to: 'noreply@colorado.edu'
        headers:
          subject: 'Prometheus Mail Alerts - Spring Application'
        require_tls: false  # Local and Testing only