route:
  receiver: 'mail'
  repeat_interval: 30s
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'mailhog:1025'
        auth_username: "none"
        auth_password: "none"
        from: 'noreply@colorado.edu'
        to: 'noreply@colorado.edu'
        headers:
          subject: 'Prometheus Mail Alerts'