version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    user: root  # or '0'
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana

  alertmanager:
    image: prom/alertmanager:v0.26.0
    container_name: alertmanager
    restart: unless-stopped
    ports:
      - "9093:9093"
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yaml --log.level=debug

  mailhog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui

  app-a:
    image: quangdo/spring-prometheus:1.0-snapshot
    container_name: app-a
    ports:
      - "9001:8888"

  app-b:
    image: quangdo/spring-prometheus:1.0-snapshot
    container_name: app-b
    ports:
      - "9002:8888"


volumes:
  prometheus-data:
  grafana-data:
  alertmanager-data:
