server:
  port: -1

# Actuator configuration
# Per https://docs-containers.colorado.edu/how_to/monitor_apps/monitoring_user_defined_projects/
# All metrics for Prometheus are scraped from a /metrics endpoint.
management:
  server:
    port: 9999
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      path-mapping:
        prometheus: metrics
      base-path: /
      discovery:
        enabled: false
      exposure:
        include:
          - health
          - info
          - prometheus