groups:
  - name: healthy
    rules:
      # Alert for any instance that is unreachable
      - alert: InstanceDown
        expr: up < 1
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes."